import { motion } from "framer-motion";
import { Camera, Edit, Sparkles, Smartphone, Upload, ArrowRight } from "lucide-react";
import type { RealityTraceStep } from "./types";

type RealityTraceProps = {
  steps: RealityTraceStep[];
};

const stepIcons: Record<string, typeof Camera> = {
  "Screenshot Captured": Smartphone,
  "Edited in Image Editor": Edit,
  "Text Modified": Edit,
  "Re-exported as Image": Upload,
  "Original Screenshot": Smartphone,
  "Text Content Edited": Edit,
  "Re-saved Multiple Times": Upload,
  "Generated by AI Model": Sparkles,
  "Post-processed": Edit,
  "Exported as Image": Upload,
  "Captured by": Camera,
  "Uploaded Directly": Upload,
};

function getIconForStep(step: string): typeof Camera {
  for (const [key, icon] of Object.entries(stepIcons)) {
    if (step.includes(key) || step.toLowerCase().includes(key.toLowerCase())) {
      return icon;
    }
  }
  return Camera;
}

export function RealityTrace({ steps }: RealityTraceProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.3 }}
      className="glass-card rounded-3xl p-6 md:p-8"
    >
      <h4 className="font-bold text-xl mb-6 flex items-center gap-3">
        <Sparkles className="w-6 h-6 text-purple" />
        Reality Trace™ - Creation Pathway
      </h4>

      <div className="flex flex-wrap items-center gap-3 md:gap-4">
        {steps.map((step, index) => {
          const Icon = getIconForStep(step.step);
          const isLast = index === steps.length - 1;

          return (
            <motion.div
              key={index}
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.1 * index + 0.4 }}
              className="flex items-center"
            >
              <div className="flex flex-col items-center">
                <div className="glass-card rounded-2xl p-4 border-cyan/20 hover:border-cyan/40 transition-colors">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan/20 to-purple/20 flex items-center justify-center mb-2">
                    <Icon className="w-6 h-6 text-cyan" />
                  </div>
                  <p className="text-sm font-medium text-center max-w-[120px] leading-tight">{step.step}</p>
                  <div className="mt-2 px-2 py-1 rounded-full bg-cyan/10 text-center">
                    <span className="text-xs font-bold text-cyan">{step.confidence}%</span>
                  </div>
                </div>
              </div>
              
              {!isLast && (
                <motion.div
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.1 * index + 0.5 }}
                  className="mx-2 md:mx-3"
                >
                  <ArrowRight className="w-5 h-5 text-muted-foreground" />
                </motion.div>
              )}
            </motion.div>
          );
        })}
      </div>
    </motion.div>
  );
}
