export type Severity = "Critical" | "High" | "Medium" | "Low" | "Good";

export type Anomaly = {
  title: string;
  description: string;
  severity: Severity;
};

export type RealityTraceStep = {
  step: string;
  confidence: number;
};

export type TruthScore = {
  risk: "HIGH" | "MEDIUM" | "LOW";
  category: string;
  impact: string;
  recommendation: string;
};

export type SourceMatch = {
  template: boolean | string;
  online: boolean;
  format: string;
};

export type AnalysisResult = {
  score: number;
  status: string;
  color: "red" | "yellow" | "green";
  anomalies: Anomaly[];
  realityTrace: RealityTraceStep[];
  truthScore: TruthScore;
  sourceMatch: SourceMatch;
  exampleImage?: string;
};

export const exampleResults: Record<string, AnalysisResult> = {
  "fake-upi": {
    score: 23,
    status: "MANIPULATION DETECTED",
    color: "red",
    anomalies: [
      {
        title: "Template Format Mismatch",
        description: "Layout doesn't match official UPI receipt structure",
        severity: "Critical"
      },
      {
        title: "Font Rendering Error",
        description: "Text font doesn't match standard UPI app fonts",
        severity: "High"
      },
      {
        title: "Missing Transaction Metadata",
        description: "Required transaction signature not found",
        severity: "Critical"
      },
      {
        title: "Timestamp Inconsistency",
        description: "Date/time format doesn't match UPI standards",
        severity: "Medium"
      }
    ],
    realityTrace: [
      { step: "Screenshot Captured", confidence: 95 },
      { step: "Edited in Image Editor", confidence: 89 },
      { step: "Text Modified", confidence: 92 },
      { step: "Re-exported as Image", confidence: 88 }
    ],
    truthScore: {
      risk: "HIGH",
      category: "Financial Fraud",
      impact: "If accepted as payment proof, this could enable fraud of ₹5,000-15,000",
      recommendation: "DO NOT accept this as valid payment confirmation. Verify through original UPI app."
    },
    sourceMatch: {
      template: false,
      online: false,
      format: "Failed 5/7 checks"
    }
  },
  "fake-whatsapp": {
    score: 31,
    status: "MANIPULATION DETECTED",
    color: "red",
    anomalies: [
      {
        title: "UI Spacing Error",
        description: "Chat bubble spacing inconsistent with WhatsApp standards",
        severity: "High"
      },
      {
        title: "Timestamp Format Wrong",
        description: "Time display doesn't match WhatsApp format",
        severity: "High"
      },
      {
        title: "Font Mismatch",
        description: "Text font differs from official WhatsApp font",
        severity: "Medium"
      },
      {
        title: "Status Icon Incorrect",
        description: "Message status indicator doesn't match app design",
        severity: "Medium"
      }
    ],
    realityTrace: [
      { step: "Original Screenshot", confidence: 78 },
      { step: "Text Content Edited", confidence: 91 },
      { step: "Re-saved Multiple Times", confidence: 85 }
    ],
    truthScore: {
      risk: "MEDIUM",
      category: "Social Manipulation",
      impact: "Could be used to falsify conversations or spread misinformation",
      recommendation: "Request original message verification through WhatsApp app"
    },
    sourceMatch: {
      template: false,
      online: false,
      format: "Failed 4/7 checks"
    }
  },
  "ai-generated": {
    score: 12,
    status: "AI-GENERATED CONTENT",
    color: "red",
    anomalies: [
      {
        title: "Diffusion Artifacts Detected",
        description: "Pattern consistent with AI generation models",
        severity: "Critical"
      },
      {
        title: "No Camera Metadata",
        description: "Missing EXIF data that real photos contain",
        severity: "Critical"
      },
      {
        title: "Synthetic Texture Patterns",
        description: "Pixel patterns match AI-generated characteristics",
        severity: "High"
      },
      {
        title: "Impossible Lighting",
        description: "Light sources don't follow physical laws",
        severity: "Medium"
      }
    ],
    realityTrace: [
      { step: "Generated by AI Model", confidence: 96 },
      { step: "Post-processed", confidence: 72 },
      { step: "Exported as Image", confidence: 94 }
    ],
    truthScore: {
      risk: "MEDIUM",
      category: "Synthetic Content / Misinformation",
      impact: "AI-generated content could be used to spread false information",
      recommendation: "Verify source and context before sharing or trusting"
    },
    sourceMatch: {
      template: "N/A",
      online: false,
      format: "No camera signature found"
    }
  }
};
