import { motion } from "framer-motion";
import { useInView } from "framer-motion";
import { useRef, useState } from "react";
import { ChevronDown, Cpu, Brain, FileSearch, Fingerprint, CheckCircle } from "lucide-react";

const techSections = [
  {
    icon: FileSearch,
    title: "Image Forensics",
    color: "from-cyan to-blue-500",
    content:
      "Error Level Analysis (ELA), chromatic aberration checks, FFT texture frequency analysis, illumination field estimation for detecting lighting inconsistencies and copy-move forgeries.",
    accuracy: 96,
    whyItMatters: "Catches pixel-level edits invisible to the human eye",
  },
  {
    icon: Brain,
    title: "AI Detection",
    color: "from-purple to-pink-500",
    content:
      "Convolutional Neural Networks spot pixel-level artifacts. Transformer models analyze synthetic patterns. Temporal consistency models catch video glitches and deepfake artifacts.",
    accuracy: 94,
    whyItMatters: "Identifies content generated by AI tools like Midjourney, DALL-E, and Stable Diffusion",
  },
  {
    icon: Cpu,
    title: "Document Analysis",
    color: "from-green-500 to-emerald-500",
    content:
      "Font consistency verification, bubble spacing analysis, timestamp pattern matching, UI color rules, layout verification, OCR structure analysis for screenshot authentication.",
    accuracy: 92,
    whyItMatters: "Detects fake UPI slips, forged WhatsApp chats, and altered documents",
  },
  {
    icon: Fingerprint,
    title: "Reality Trace Engine",
    color: "from-orange-500 to-yellow-500",
    content:
      "Diffusion fingerprints detection, pixel-neighborhood graphs, recompression path mapping, signature residue detection to reconstruct the complete creation history.",
    accuracy: 91,
    whyItMatters: "Shows exactly how content was created and modified over time",
  },
];

export function Technology() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section className="relative py-32 lg:py-40 overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0">
        <div className="absolute top-1/2 right-1/4 w-[600px] h-[600px] bg-purple/5 rounded-full blur-[180px]" />
      </div>
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-border to-transparent" />

      <div ref={ref} className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-card mb-8">
            <Cpu className="w-4 h-4 text-purple" />
            <span className="text-sm font-medium text-muted-foreground">Technology</span>
          </div>
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6">
            Powered By Advanced{" "}
            <span className="text-gradient-vibrant">Forensic Science</span>
          </h2>
          <p className="text-lg text-muted-foreground">
            State-of-the-art detection methods simplified for everyone
          </p>
        </motion.div>

        {/* Accordion - Enhanced card style */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="space-y-4"
        >
          {techSections.map((section, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className={`glass-card rounded-2xl overflow-hidden transition-all duration-300 ${openIndex === index ? 'border-l-4' : ''}`}
              style={{ borderLeftColor: openIndex === index ? `hsl(var(--${section.color.includes('cyan') ? 'cyan' : section.color.includes('purple') ? 'purple' : 'primary'}))` : 'transparent' }}
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full p-6 flex items-center gap-5 text-left hover:bg-muted/30 transition-colors"
              >
                {/* Icon with gradient */}
                <div className={`w-14 h-14 rounded-xl bg-gradient-to-br ${section.color} p-0.5 shrink-0`}>
                  <div className="w-full h-full rounded-xl bg-background flex items-center justify-center">
                    <section.icon className="w-6 h-6 text-foreground" />
                  </div>
                </div>
                <div className="flex-1">
                  <span className="font-bold text-lg">{section.title}</span>
                  {openIndex !== index && (
                    <p className="text-sm text-muted-foreground mt-1 line-clamp-1">{section.whyItMatters}</p>
                  )}
                </div>
                <ChevronDown
                  className={`w-6 h-6 text-muted-foreground transition-transform duration-300 ${
                    openIndex === index ? "rotate-180" : ""
                  }`}
                />
              </button>
              <motion.div
                initial={false}
                animate={{
                  height: openIndex === index ? "auto" : 0,
                  opacity: openIndex === index ? 1 : 0,
                }}
                transition={{ duration: 0.3 }}
                className="overflow-hidden"
              >
                <div className="px-6 pb-6 space-y-5">
                  {/* Expanded content with gradient background */}
                  <div className={`p-5 rounded-xl bg-gradient-to-r ${section.color} bg-opacity-5`} style={{ background: `linear-gradient(135deg, hsl(var(--muted) / 0.5), hsl(var(--muted) / 0.3))` }}>
                    <p className="text-muted-foreground leading-relaxed text-base">
                      {section.content}
                    </p>
                  </div>
                  
                  {/* Why it matters */}
                  <div className="flex items-start gap-3">
                    <CheckCircle className="w-5 h-5 text-cyan mt-0.5 shrink-0" />
                    <div>
                      <span className="text-sm font-semibold text-cyan">Why This Matters:</span>
                      <p className="text-sm text-muted-foreground mt-1">{section.whyItMatters}</p>
                    </div>
                  </div>
                  
                  {/* Accuracy bar */}
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">Detection Accuracy</span>
                      <span className="font-bold text-gradient">{section.accuracy}%</span>
                    </div>
                    <div className="h-2 rounded-full bg-muted overflow-hidden">
                      <motion.div
                        initial={{ width: 0 }}
                        animate={{ width: openIndex === index ? `${section.accuracy}%` : 0 }}
                        transition={{ duration: 1, delay: 0.2 }}
                        className={`h-full rounded-full bg-gradient-to-r ${section.color}`}
                      />
                    </div>
                  </div>
                </div>
              </motion.div>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}